# SDG Indicators with Codes
SDG_MAP = {
    "SDG 2": [
        "2.1.1 Prevalence of undernourishment (%)",
        "2.2.1 Prevalence of stunting (height for age <-2 SD) (%)",
    ],
    "SDG 3": [
        "3.1.1 Maternal Mortality Ratio (per 100k births)",
        "3.2.1 Under-5 Mortality Rate (per 1,000 live births)",
    ],
    "SDG 6": [
        "6.1.1 Proportion of population using safely managed drinking water services (%)",
        "6.2.1 Proportion of population using safely managed sanitation services (%)",
    ],
}

# Mapping old names to new names for data compatibility
# Keys must match exactly what is in the CSV generated by generate_mock_data.py
INDICATOR_RENAME_MAP = {
    "Prevalence of Undernourishment (%)": "2.1.2 Prevalence of moderate or severe food insecurity (%)",
    "Stunting in Children < 5 Years (%)": "2.2.1 Prevalence of stunting (height for age <-2 SD) (%)",
    "Maternal Mortality Ratio (per 100k births)": "3.1.1 Maternal Mortality Ratio (per 100k births)",
    "Under-5 Mortality Rate (per 1,000 live births)": "3.2.1 Under-5 Mortality Rate (per 1,000 live births)",
    "Safely Managed Drinking Water (%)": "6.1.1 Proportion of population using safely managed drinking water services (%)",
    "Open Defecation Practice (%)": "6.2.1 Proportion of population using safely managed sanitation services (%)",
}

import os
import base64


# Helper to get local asset path
def get_asset_path(filename):
    # This assumes running from project root (SDG_Analytics_Project) or appSDG folder
    # We will return a path relative to the script execution or absolute if safest
    return os.path.join("appSDG", "assets", filename)


def get_img_as_base64(file_path):
    """
    Reads an image file and returns a base64 encoded string.
    """
    try:
        with open(file_path, "rb") as f:
            data = f.read()
        return base64.b64encode(data).decode()
    except Exception as e:
        return ""


# Icon Paths (Local Assets)
ICON_URLS = {
    "SDG 2": "appSDG/assets/sdg2.png",
    "SDG 3": "appSDG/assets/sdg3.png",
    "SDG 6": "appSDG/assets/sdg6.png",
    "Main": "appSDG/assets/sdg_main.png",
}
